### ISSUE TITLE
Replace static event pages with generated versions

### ISSUE THREAD

**Issue by Bertg** [railsgirls/railsgirls.com#557]
# Problem

As per https://github.com/railsgirls/railsgirls/issues/556 generating a new event is painful because the following steps need to happen:
- Create new event static page
- Update index page to show upcoming events
  - These events aren't guaranteed to be ordered correctly
  - They might not even be relevant anymore, and require manual curation to fix these discrepancies
- Update events page with link to newly created event
  - See above
## Solution

Move over to using jekyll to build a friendlier and more reliable event information
- [ ] Create contribution guide for adding new events (@csaunders in #562)
- [x] Automatically show events that are upcoming on index
- [ ] Automatically show events on the events page
- [ ] Migrate existing events to new system (@andreionut in #559)
- [ ] Extract basic template to reduce duplication (@mvz in #559)
- [ ] Forward from old URLs to new URLs using `meta refresh` or Javascript to preserve SEO
